### ISSUE TITLE
Trim View display only first frame

### ISSUE THREAD

**Issue by barbaragomes** [shahen94/react-native-video-processing#33]
I have notice that the trimming component replicates the first frame of the video over and over again. Is it right, or is it something that I'm doing wrong?

For example, if my video starts with a black screen,  the trimming view shows as completely black.

**Comment by shahen94** [comment]
thanks for reporting this problem @barbaragomes , this happens sometimes,
https://github.com/shahen94/react-native-video-processing/blob/master/ios/RNVideoProcessing/RNTrimmerView/RNTrimmerView.swift#L123
i believe we have to call this fn in other flaces too.

currently i have no time to fix this issue, since i've focused on android version

**Comment by barbaragomes** [comment]
@shahen94 thank you very much for your reply.

This issue is happening to me all times.

I will take sometime to see if I can fix it =)

**Comment by shahen94** [comment]
Thank you @barbaragomes !
I'll take a time to take a look at this issue when android version will be ready.(in next week)

**Comment by shahen94** [comment]
@barbaragomes this issue has been fixed due to this commit
https://github.com/shahen94/react-native-video-processing/commit/f1eca469

I'm going to close this, so feel free to reopen it

**Comment by barbaragomes** [comment]
@shahen94 Thank you very much! It is now working for me =)
